// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Sea subsurface.tsv (APP-6 DE)

package app6d

// Entity constants for symbol set 35 (Sea subsurface).
const (
	EntitySeaSubsurface_Military                                                           Entity = 110000 // Military
	EntitySeaSubsurface_MilitarySubmarine                                                  Entity = 110100 // Military / Submarine
	EntitySeaSubsurface_MilitarySubmarineSubmarineSurfaced                                 Entity = 110101 // Military / Submarine / Submarine, Surfaced
	EntitySeaSubsurface_MilitarySubmarineSubmarineSnorkeling                               Entity = 110102 // Military / Submarine / Submarine, Snorkeling
	EntitySeaSubsurface_MilitarySubmarineSubmarineBottomed                                 Entity = 110103 // Military / Submarine / Submarine, Bottomed
	EntitySeaSubsurface_MilitaryOtherSubmersible                                           Entity = 110200 // Military / Other Submersible
	EntitySeaSubsurface_MilitaryNonsubmarine                                               Entity = 110300 // Military / Nonsubmarine
	EntitySeaSubsurface_MilitaryAutonomousUnderwaterVehicleAUVUnmannedUnderwaterVehicleUUV Entity = 110400 // Military / Autonomous Underwater Vehicle (AUV)/Unmanned Underwater Vehicle (UUV)
	EntitySeaSubsurface_MilitaryDiver                                                      Entity = 110500 // Military / Diver
	EntitySeaSubsurface_Civilian                                                           Entity = 120000 // Civilian
	EntitySeaSubsurface_CivilianSubmersible                                                Entity = 120100 // Civilian / Submersible
	EntitySeaSubsurface_CivilianAutonomousUnderwaterVehicleAUVUnmannedUnderwaterVehicleUUV Entity = 120200 // Civilian / Autonomous Underwater Vehicle (AUV)/ Unmanned Underwater Vehicle (UUV)
	EntitySeaSubsurface_CivilianDiver                                                      Entity = 120300 // Civilian / Diver
	EntitySeaSubsurface_Weapon                                                             Entity = 130000 // Weapon
	EntitySeaSubsurface_WeaponTorpedo                                                      Entity = 130100 // Weapon / Torpedo
	EntitySeaSubsurface_WeaponImprovisedExplosiveDeviceIED                                 Entity = 130200 // Weapon / Improvised Explosive Device (IED)
	EntitySeaSubsurface_WeaponDecoy                                                        Entity = 130300 // Weapon / Decoy
	EntitySeaSubsurface_EchoTrackerClassifierETCPossibleContactPOSCON                      Entity = 140000 // Echo Tracker Classifier (ETC) / Possible Contact (POSCON)
	EntitySeaSubsurface_FusedTrack                                                         Entity = 150000 // Fused Track
	EntitySeaSubsurface_ManualTrack                                                        Entity = 160000 // Manual Track
	EntitySeaSubsurface_SeabedInstallationManMadeMilitary                                  Entity = 200000 // Seabed Installation Man-Made, Military
	EntitySeaSubsurface_SeabedInstallationManMadeNonMilitary                               Entity = 210000 // Seabed Installation Man-Made, Non-Military
)
