// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Land civilian.tsv (APP-6 DE)

package app6d

// Entity constants for symbol set 11 (Land civilian).
const (
	// EntityLandCivilian_Civilian is Civilian.
	EntityLandCivilian_Civilian Entity = 110000

	// EntityLandCivilian_CivilianEnvironmentalProtection is Civilian / Environmental Protection.
	EntityLandCivilian_CivilianEnvironmentalProtection Entity = 110100

	// EntityLandCivilian_CivilianGovernmentOrganization is Civilian / Government Organization.
	EntityLandCivilian_CivilianGovernmentOrganization Entity = 110200

	// EntityLandCivilian_CivilianIndividual is Civilian / Individual.
	EntityLandCivilian_CivilianIndividual Entity = 110300

	// EntityLandCivilian_CivilianOrganizationOrGroup is Civilian / Organization or Group.
	EntityLandCivilian_CivilianOrganizationOrGroup Entity = 110400

	// EntityLandCivilian_CivilianKillingVictim is Civilian / Killing Victim.
	EntityLandCivilian_CivilianKillingVictim Entity = 110500

	// EntityLandCivilian_CivilianKillingVictims is Civilian / Killing Victims.
	EntityLandCivilian_CivilianKillingVictims Entity = 110600

	// EntityLandCivilian_CivilianVictimOfAnAttemptedCrime is Civilian / Victim of an Attempted Crime.
	EntityLandCivilian_CivilianVictimOfAnAttemptedCrime Entity = 110700

	// EntityLandCivilian_CivilianSpy is Civilian / Spy.
	EntityLandCivilian_CivilianSpy Entity = 110800

	// EntityLandCivilian_CivilianCompositeLoss is Civilian / Composite Loss.
	EntityLandCivilian_CivilianCompositeLoss Entity = 110900

	// EntityLandCivilian_CivilianEmergencyMedicalOperation is Civilian / Emergency Medical Operation.
	EntityLandCivilian_CivilianEmergencyMedicalOperation Entity = 111000
)
