// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Air.tsv (APP-6 DE)

package app6d

// Entity constants for symbol set 01 (Air).
const (
	EntityAir_Military                                                                                             Entity = 110000 // Military
	EntityAir_MilitaryFixedWing                                                                                    Entity = 110100 // Military / Fixed Wing
	EntityAir_MilitaryFixedWingMedicalEvacuationMEDEVAC                                                            Entity = 110101 // Military / Fixed Wing / Medical Evacuation (MEDEVAC)
	EntityAir_MilitaryFixedWingAttackStrike                                                                        Entity = 110102 // Military / Fixed Wing / Attack/Strike
	EntityAir_MilitaryFixedWingBomber                                                                              Entity = 110103 // Military / Fixed Wing / Bomber
	EntityAir_MilitaryFixedWingFighter                                                                             Entity = 110104 // Military / Fixed Wing / Fighter
	EntityAir_MilitaryFixedWingFighterBomber                                                                       Entity = 110105 // Military / Fixed Wing / Fighter/Bomber
	EntityAir_MilitaryFixedWingDisused                                                                             Entity = 110106 // Military / Fixed Wing / {Disused}
	EntityAir_MilitaryFixedWingCargo                                                                               Entity = 110107 // Military / Fixed Wing / Cargo
	EntityAir_MilitaryFixedWingElectronicCombatECJammer                                                            Entity = 110108 // Military / Fixed Wing / Electronic Combat (EC)/Jammer
	EntityAir_MilitaryFixedWingTanker                                                                              Entity = 110109 // Military / Fixed Wing / Tanker
	EntityAir_MilitaryFixedWingPatrol                                                                              Entity = 110110 // Military / Fixed Wing / Patrol
	EntityAir_MilitaryFixedWingReconnaissance                                                                      Entity = 110111 // Military / Fixed Wing / Reconnaissance
	EntityAir_MilitaryFixedWingTrainer                                                                             Entity = 110112 // Military / Fixed Wing / Trainer
	EntityAir_MilitaryFixedWingUtility                                                                             Entity = 110113 // Military / Fixed Wing / Utility
	EntityAir_MilitaryFixedWingVerticalOrShortTakeOffAndLandingVSTOL                                               Entity = 110114 // Military / Fixed Wing / Vertical or Short Take-off and Landing (VSTOL)
	EntityAir_MilitaryFixedWingAirborneCommandPostACP                                                              Entity = 110115 // Military / Fixed Wing / Airborne Command Post (ACP)
	EntityAir_MilitaryFixedWingAirborneEarlyWarningAEW                                                             Entity = 110116 // Military / Fixed Wing / Airborne Early Warning (AEW)
	EntityAir_MilitaryFixedWingAntisurfaceWarfare                                                                  Entity = 110117 // Military / Fixed Wing / Antisurface Warfare
	EntityAir_MilitaryFixedWingAntisubmarineWarfare                                                                Entity = 110118 // Military / Fixed Wing / Antisubmarine Warfare
	EntityAir_MilitaryFixedWingCommunications                                                                      Entity = 110119 // Military / Fixed Wing / Communications
	EntityAir_MilitaryFixedWingCombatSearchAndRescueCSAR                                                           Entity = 110120 // Military / Fixed Wing / Combat Search and Rescue (CSAR)
	EntityAir_MilitaryFixedWingElectronicSupportES                                                                 Entity = 110121 // Military / Fixed Wing / Electronic Support (ES)
	EntityAir_MilitaryFixedWingGovernment                                                                          Entity = 110122 // Military / Fixed Wing / Government
	EntityAir_MilitaryFixedWingMineCountermeasuresMCM                                                              Entity = 110123 // Military / Fixed Wing / Mine Countermeasures (MCM)
	EntityAir_MilitaryFixedWingPersonnelRecovery                                                                   Entity = 110124 // Military / Fixed Wing / Personnel Recovery
	EntityAir_MilitaryFixedWingSearchAndRescue                                                                     Entity = 110125 // Military / Fixed Wing / Search and Rescue
	EntityAir_MilitaryFixedWingSpecialOperationsForces                                                             Entity = 110126 // Military / Fixed Wing / Special Operations Forces
	EntityAir_MilitaryFixedWingUltraLight                                                                          Entity = 110127 // Military / Fixed Wing / Ultra Light
	EntityAir_MilitaryFixedWingPhotographicReconnaissance                                                          Entity = 110128 // Military / Fixed Wing / Photographic Reconnaissance
	EntityAir_MilitaryFixedWingVeryImportantPersonVIP                                                              Entity = 110129 // Military / Fixed Wing / Very Important Person (VIP)
	EntityAir_MilitaryFixedWingSuppressionOfEnemyAirDefense                                                        Entity = 110130 // Military / Fixed Wing / Suppression of Enemy Air Defense
	EntityAir_MilitaryFixedWingPassenger                                                                           Entity = 110131 // Military / Fixed Wing / Passenger
	EntityAir_MilitaryFixedWingEscort                                                                              Entity = 110132 // Military / Fixed Wing / Escort
	EntityAir_MilitaryFixedWingElectronicAttackEA                                                                  Entity = 110133 // Military / Fixed Wing / Electronic Attack (EA)
	EntityAir_MilitaryRotaryWing                                                                                   Entity = 110200 // Military / Rotary Wing
	EntityAir_MilitaryUnmannedAircraftUAUnmannedAerialVehicleUAVUnmannedAircraftSystemUASRemotelyPilotedVehicleRPV Entity = 110300 // Military / Unmanned Aircraft (UA) / Unmanned Aerial Vehicle (UAV) / Unmanned Aircraft System (UAS) / Remotely Piloted Vehicle (RPV)
	EntityAir_MilitaryVerticalTakeoffUAVVTUAV                                                                      Entity = 110400 // Military / Vertical–Takeoff UAV (VT–UAV)
	EntityAir_MilitaryLighterThanAir                                                                               Entity = 110500 // Military / Lighter Than Air
	EntityAir_MilitaryAirship                                                                                      Entity = 110600 // Military / Airship
	EntityAir_MilitaryTetheredLighterThanAir                                                                       Entity = 110700 // Military / Tethered Lighter than Air
	EntityAir_Civilian                                                                                             Entity = 120000 // Civilian
	EntityAir_CivilianFixedWing                                                                                    Entity = 120100 // Civilian / Fixed Wing
	EntityAir_CivilianRotaryWing                                                                                   Entity = 120200 // Civilian / Rotary Wing
	EntityAir_CivilianUnmannedAircraftUAUnmannedAerialVehicleUAVUnmannedAircraftSystemUASRemotelyPilotedVehicleRPV Entity = 120300 // Civilian / Unmanned Aircraft (UA) / Unmanned Aerial Vehicle (UAV) / Unmanned Aircraft System (UAS) / Remotely Piloted Vehicle (RPV)
	EntityAir_CivilianLighterThanAir                                                                               Entity = 120400 // Civilian / Lighter Than Air
	EntityAir_CivilianAirship                                                                                      Entity = 120500 // Civilian / Airship
	EntityAir_CivilianTetheredLighterThanAir                                                                       Entity = 120600 // Civilian / Tethered Lighter than Air
	EntityAir_CivilianMedicalEvacuationMEDEVAC                                                                     Entity = 120700 // Civilian / Medical Evacuation (MEDEVAC)
	EntityAir_Weapon                                                                                               Entity = 130000 // Weapon
	EntityAir_WeaponBomb                                                                                           Entity = 130100 // Weapon / Bomb
	EntityAir_WeaponDecoy                                                                                          Entity = 130200 // Weapon / Decoy
	EntityAir_ManualTrackManualTrack                                                                               Entity = 140000 // Manual Track / Manual Track
)
