// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Air missile.tsv (APP-6 DE)

package app6d

// Entity constants for symbol set 02 (Air missile).
const (
	EntityAirMissile_Missile Entity = 110000 // Missile
)
