// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 51 (Signals intelligence).
const (
	// EntitySIGINTAir_SignalInterceptSignalIntercept is Signal Intercept / Signal Intercept.
	EntitySIGINTAir_SignalInterceptSignalIntercept Entity = 110000

	// EntitySIGINTAir_SignalInterceptCommunications is Signal Intercept / Communications.
	EntitySIGINTAir_SignalInterceptCommunications Entity = 110100

	// EntitySIGINTAir_SignalInterceptJammer is Signal Intercept / Jammer.
	EntitySIGINTAir_SignalInterceptJammer Entity = 110200

	// EntitySIGINTAir_SignalInterceptRadar is Signal Intercept / Radar.
	EntitySIGINTAir_SignalInterceptRadar Entity = 110300
)
