// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 54 (Signals intelligence).
const (
	// EntitySIGINTSubsurface_SignalInterceptSignalIntercept is Signal Intercept / Signal Intercept.
	EntitySIGINTSubsurface_SignalInterceptSignalIntercept Entity = 110000

	// EntitySIGINTSubsurface_SignalInterceptCommunications is Signal Intercept / Communications.
	EntitySIGINTSubsurface_SignalInterceptCommunications Entity = 110100

	// EntitySIGINTSubsurface_SignalInterceptJammer is Signal Intercept / Jammer.
	EntitySIGINTSubsurface_SignalInterceptJammer Entity = 110200

	// EntitySIGINTSubsurface_SignalInterceptRadar is Signal Intercept / Radar.
	EntitySIGINTSubsurface_SignalInterceptRadar Entity = 110300
)
