// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 51 (Signals intelligence).
const (
	EntitySIGINTAir_SignalInterceptSignalIntercept Entity = 110000 // Signal Intercept / Signal Intercept
	EntitySIGINTAir_SignalInterceptCommunications  Entity = 110100 // Signal Intercept / Communications
	EntitySIGINTAir_SignalInterceptJammer          Entity = 110200 // Signal Intercept / Jammer
	EntitySIGINTAir_SignalInterceptRadar           Entity = 110300 // Signal Intercept / Radar
)
