// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 50 (Signals intelligence).
const (
	// EntitySIGINTSpace_SignalInterceptSignalIntercept is Signal Intercept / Signal Intercept.
	EntitySIGINTSpace_SignalInterceptSignalIntercept Entity = 110000

	// EntitySIGINTSpace_SignalInterceptCommunications is Signal Intercept / Communications.
	EntitySIGINTSpace_SignalInterceptCommunications Entity = 110100

	// EntitySIGINTSpace_SignalInterceptJammer is Signal Intercept / Jammer.
	EntitySIGINTSpace_SignalInterceptJammer Entity = 110200

	// EntitySIGINTSpace_SignalInterceptRadar is Signal Intercept / Radar.
	EntitySIGINTSpace_SignalInterceptRadar Entity = 110300
)
