// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 53 (Signals intelligence).
const (
	EntitySIGINTSeaSurface_SignalInterceptSignalIntercept Entity = 110000 // Signal Intercept / Signal Intercept
	EntitySIGINTSeaSurface_SignalInterceptCommunications  Entity = 110100 // Signal Intercept / Communications
	EntitySIGINTSeaSurface_SignalInterceptJammer          Entity = 110200 // Signal Intercept / Jammer
	EntitySIGINTSeaSurface_SignalInterceptRadar           Entity = 110300 // Signal Intercept / Radar
)
