// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Mine warfare.tsv (APP-6 DE)

package app6d

// Entity constants for symbol set 36 (Mine warfare).
const (
	EntityMineWarfare_SeaMineGeneral                                                   Entity = 110000 // Sea Mine, General
	EntityMineWarfare_SeaMineGeneralSeaMineBottom                                      Entity = 110100 // Sea Mine, General / Sea Mine, Bottom
	EntityMineWarfare_SeaMineGeneralSeaMineMoored                                      Entity = 110200 // Sea Mine, General / Sea Mine, Moored
	EntityMineWarfare_SeaMineGeneralSeaMineFloating                                    Entity = 110300 // Sea Mine, General / Sea Mine, Floating
	EntityMineWarfare_SeaMineGeneralSeaMineRising                                      Entity = 110400 // Sea Mine, General / Sea Mine, Rising
	EntityMineWarfare_SeaMineGeneralSeaMineOtherPosition                               Entity = 110500 // Sea Mine, General / Sea Mine, Other Position
	EntityMineWarfare_SeaMineGeneralKingfisher                                         Entity = 110600 // Sea Mine, General / Kingfisher
	EntityMineWarfare_SeaMineGeneralSmallObjectMineLike                                Entity = 110700 // Sea Mine, General / Small Object, Mine–Like
	EntityMineWarfare_SeaMineGeneralExerciseMineGeneral                                Entity = 110800 // Sea Mine, General / Exercise Mine, General
	EntityMineWarfare_SeaMineGeneralExerciseMineGeneralExerciseMineBottom              Entity = 110801 // Sea Mine, General / Exercise Mine, General / Exercise Mine, Bottom
	EntityMineWarfare_SeaMineGeneralExerciseMineGeneralExerciseMineMoored              Entity = 110802 // Sea Mine, General / Exercise Mine, General / Exercise Mine, Moored
	EntityMineWarfare_SeaMineGeneralExerciseMineGeneralExerciseMineFloating            Entity = 110803 // Sea Mine, General / Exercise Mine, General / Exercise Mine, Floating
	EntityMineWarfare_SeaMineGeneralExerciseMineGeneralExerciseMineRising              Entity = 110804 // Sea Mine, General / Exercise Mine, General / Exercise Mine, Rising
	EntityMineWarfare_SeaMineGeneralNeutralizedMineGeneral                             Entity = 110900 // Sea Mine, General / Neutralized Mine, General
	EntityMineWarfare_SeaMineGeneralNeutralizedMineGeneralNeutralizedMineBottom        Entity = 110901 // Sea Mine, General / Neutralized Mine, General / Neutralized Mine, Bottom
	EntityMineWarfare_SeaMineGeneralNeutralizedMineGeneralNeutralizedMineMoored        Entity = 110902 // Sea Mine, General / Neutralized Mine, General / Neutralized Mine, Moored
	EntityMineWarfare_SeaMineGeneralNeutralizedMineGeneralNeutralizedMineFloating      Entity = 110903 // Sea Mine, General / Neutralized Mine, General / Neutralized Mine, Floating
	EntityMineWarfare_SeaMineGeneralNeutralizedMineGeneralNeutralizedMineRising        Entity = 110904 // Sea Mine, General / Neutralized Mine, General / Neutralized Mine, Rising
	EntityMineWarfare_SeaMineGeneralNeutralizedMineGeneralNeutralizedMineOtherPosition Entity = 110905 // Sea Mine, General / Neutralized Mine, General / Neutralized Mine, Other Position
	EntityMineWarfare_UnexplodedOrdnance                                               Entity = 120000 // Unexploded Ordnance
	EntityMineWarfare_SeaMineDecoy                                                     Entity = 130000 // Sea Mine Decoy
	EntityMineWarfare_SeaMineDecoySeaMineDecoyBottom                                   Entity = 130100 // Sea Mine Decoy / Sea Mine Decoy, Bottom
	EntityMineWarfare_SeaMineDecoySeaMineDecoyMoored                                   Entity = 130200 // Sea Mine Decoy / Sea Mine Decoy, Moored
	EntityMineWarfare_MineLikeContactMILCO                                             Entity = 140000 // Mine–Like Contact (MILCO)
	EntityMineWarfare_MineLikeContactMILCOMILCOGeneral                                 Entity = 140100 // Mine–Like Contact (MILCO) / MILCO - General
	EntityMineWarfare_MineLikeContactMILCOMILCOGeneralMILCOGeneralConfidenceLevel1     Entity = 140101 // Mine–Like Contact (MILCO) / MILCO - General / MILCO - General, Confidence Level 1
	EntityMineWarfare_MineLikeContactMILCOMILCOGeneralMILCOGeneralConfidenceLevel2     Entity = 140102 // Mine–Like Contact (MILCO) / MILCO - General / MILCO - General, Confidence Level 2
	EntityMineWarfare_MineLikeContactMILCOMILCOGeneralMILCOGeneralConfidenceLevel3     Entity = 140103 // Mine–Like Contact (MILCO) / MILCO - General / MILCO - General, Confidence Level 3
	EntityMineWarfare_MineLikeContactMILCOMILCOGeneralMILCOGeneralConfidenceLevel4     Entity = 140104 // Mine–Like Contact (MILCO) / MILCO - General / MILCO - General, Confidence Level 4
	EntityMineWarfare_MineLikeContactMILCOMILCOGeneralMILCOGeneralConfidenceLevel5     Entity = 140105 // Mine–Like Contact (MILCO) / MILCO - General / MILCO - General, Confidence Level 5
	EntityMineWarfare_MineLikeContactMILCOMILCOBottom                                  Entity = 140200 // Mine–Like Contact (MILCO) / MILCO - Bottom
	EntityMineWarfare_MineLikeContactMILCOMILCOBottomMILCOBottomConfidenceLevel1       Entity = 140201 // Mine–Like Contact (MILCO) / MILCO - Bottom / MILCO - Bottom, Confidence Level 1
	EntityMineWarfare_MineLikeContactMILCOMILCOBottomMILCOBottomConfidenceLevel2       Entity = 140202 // Mine–Like Contact (MILCO) / MILCO - Bottom / MILCO - Bottom, Confidence Level 2
	EntityMineWarfare_MineLikeContactMILCOMILCOBottomMILCOBottomConfidenceLevel3       Entity = 140203 // Mine–Like Contact (MILCO) / MILCO - Bottom / MILCO - Bottom, Confidence Level 3
	EntityMineWarfare_MineLikeContactMILCOMILCOBottomMILCOBottomConfidenceLevel4       Entity = 140204 // Mine–Like Contact (MILCO) / MILCO - Bottom / MILCO - Bottom, Confidence Level 4
	EntityMineWarfare_MineLikeContactMILCOMILCOBottomMILCOBottomConfidenceLevel5       Entity = 140205 // Mine–Like Contact (MILCO) / MILCO - Bottom / MILCO - Bottom, Confidence Level 5
	EntityMineWarfare_MineLikeContactMILCOMILCOMoored                                  Entity = 140300 // Mine–Like Contact (MILCO) / MILCO - Moored
	EntityMineWarfare_MineLikeContactMILCOMILCOMooredMILCOMooredConfidenceLevel1       Entity = 140301 // Mine–Like Contact (MILCO) / MILCO - Moored / MILCO - Moored, Confidence Level 1
	EntityMineWarfare_MineLikeContactMILCOMILCOMooredMILCOMooredConfidenceLevel2       Entity = 140302 // Mine–Like Contact (MILCO) / MILCO - Moored / MILCO - Moored, Confidence Level 2
	EntityMineWarfare_MineLikeContactMILCOMILCOMooredMILCOMooredConfidenceLevel3       Entity = 140303 // Mine–Like Contact (MILCO) / MILCO - Moored / MILCO - Moored, Confidence Level 3
	EntityMineWarfare_MineLikeContactMILCOMILCOMooredMILCOMooredConfidenceLevel4       Entity = 140304 // Mine–Like Contact (MILCO) / MILCO - Moored / MILCO - Moored, Confidence Level 4
	EntityMineWarfare_MineLikeContactMILCOMILCOMooredMILCOMooredConfidenceLevel5       Entity = 140305 // Mine–Like Contact (MILCO) / MILCO - Moored / MILCO - Moored, Confidence Level 5
	EntityMineWarfare_MineLikeContactMILCOMILCOFloating                                Entity = 140400 // Mine–Like Contact (MILCO) / MILCO - Floating
	EntityMineWarfare_MineLikeContactMILCOMILCOFloatingMILCOFloatingConfidenceLevel1   Entity = 140401 // Mine–Like Contact (MILCO) / MILCO - Floating / MILCO - Floating, Confidence Level 1
	EntityMineWarfare_MineLikeContactMILCOMILCOFloatingMILCOFloatingConfidenceLevel2   Entity = 140402 // Mine–Like Contact (MILCO) / MILCO - Floating / MILCO - Floating, Confidence Level 2
	EntityMineWarfare_MineLikeContactMILCOMILCOFloatingMILCOFloatingConfidenceLevel3   Entity = 140403 // Mine–Like Contact (MILCO) / MILCO - Floating / MILCO - Floating, Confidence Level 3
	EntityMineWarfare_MineLikeContactMILCOMILCOFloatingMILCOFloatingConfidenceLevel4   Entity = 140404 // Mine–Like Contact (MILCO) / MILCO - Floating / MILCO - Floating, Confidence Level 4
	EntityMineWarfare_MineLikeContactMILCOMILCOFloatingMILCOFloatingConfidenceLevel5   Entity = 140405 // Mine–Like Contact (MILCO) / MILCO - Floating / MILCO - Floating, Confidence Level 5
	EntityMineWarfare_MineLikeEchoMILECGeneral                                         Entity = 150000 // Mine–Like Echo (MILEC), General
	EntityMineWarfare_MineLikeEchoMILECGeneralMineLikeEchoBottom                       Entity = 150100 // Mine–Like Echo (MILEC), General / Mine–Like Echo, Bottom
	EntityMineWarfare_MineLikeEchoMILECGeneralMineLikeEchoMoored                       Entity = 150200 // Mine–Like Echo (MILEC), General / Mine–Like Echo, Moored
	EntityMineWarfare_MineLikeEchoMILECGeneralMineLikeEchoFloating                     Entity = 150300 // Mine–Like Echo (MILEC), General / Mine–Like Echo, Floating
	EntityMineWarfare_NegativeReacquisitionGeneral                                     Entity = 160000 // Negative Reacquisition, General
	EntityMineWarfare_NegativeReacquisitionGeneralNegativeReacquisitionBottom          Entity = 160100 // Negative Reacquisition, General / Negative Reacquisition, Bottom
	EntityMineWarfare_NegativeReacquisitionGeneralNegativeReacquisitionMoored          Entity = 160200 // Negative Reacquisition, General / Negative Reacquisition, Moored
	EntityMineWarfare_NegativeReacquisitionGeneralNegativeReacquisitionFloating        Entity = 160300 // Negative Reacquisition, General / Negative Reacquisition, Floating
	EntityMineWarfare_Obstructor                                                       Entity = 170000 // Obstructor
	EntityMineWarfare_ObstructorNeutralizedObstructor                                  Entity = 170100 // Obstructor / Neutralized Obstructor
	EntityMineWarfare_GeneralMineAnchor                                                Entity = 180000 // General Mine Anchor
	EntityMineWarfare_NonMineMineLikeObjectNMLOGeneral                                 Entity = 190000 // Non-Mine Mine–Like Object (NMLO), General
	EntityMineWarfare_NonMineMineLikeObjectNMLOGeneralNonMineMineLikeObjectBottom      Entity = 190100 // Non-Mine Mine–Like Object (NMLO), General / Non-Mine Mine–Like Object, Bottom
	EntityMineWarfare_NonMineMineLikeObjectNMLOGeneralNonMineMineLikeObjectMoored      Entity = 190200 // Non-Mine Mine–Like Object (NMLO), General / Non-Mine Mine–Like Object, Moored
	EntityMineWarfare_NonMineMineLikeObjectNMLOGeneralNonMineMineLikeObjectFloating    Entity = 190300 // Non-Mine Mine–Like Object (NMLO), General / Non-Mine Mine–Like Object, Floating
	EntityMineWarfare_EnvironmentalReportLocation                                      Entity = 200000 // Environmental Report Location
	EntityMineWarfare_DiveReportLocation                                               Entity = 210000 // Dive Report Location
)
