// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 54 (Signals intelligence).
const (
	EntitySIGINTSubsurface_SignalInterceptSignalIntercept Entity = 110000 // Signal Intercept / Signal Intercept
	EntitySIGINTSubsurface_SignalInterceptCommunications  Entity = 110100 // Signal Intercept / Communications
	EntitySIGINTSubsurface_SignalInterceptJammer          Entity = 110200 // Signal Intercept / Jammer
	EntitySIGINTSubsurface_SignalInterceptRadar           Entity = 110300 // Signal Intercept / Radar
)
