// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 52 (Signals intelligence).
const (
	EntitySIGINTLand_SignalInterceptSignalIntercept Entity = 110000 // Signal Intercept / Signal Intercept
	EntitySIGINTLand_SignalInterceptCommunications  Entity = 110100 // Signal Intercept / Communications
	EntitySIGINTLand_SignalInterceptJammer          Entity = 110200 // Signal Intercept / Jammer
	EntitySIGINTLand_SignalInterceptRadar           Entity = 110300 // Signal Intercept / Radar
)
