// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Land civilian.tsv (APP-6 DE)

package app6d

// Entity constants for symbol set 11 (Land civilian).
const (
	EntityLandCivilian_Civilian                          Entity = 110000 // Civilian
	EntityLandCivilian_CivilianEnvironmentalProtection   Entity = 110100 // Civilian / Environmental Protection
	EntityLandCivilian_CivilianGovernmentOrganization    Entity = 110200 // Civilian / Government Organization
	EntityLandCivilian_CivilianIndividual                Entity = 110300 // Civilian / Individual
	EntityLandCivilian_CivilianOrganizationOrGroup       Entity = 110400 // Civilian / Organization or Group
	EntityLandCivilian_CivilianKillingVictim             Entity = 110500 // Civilian / Killing Victim
	EntityLandCivilian_CivilianKillingVictims            Entity = 110600 // Civilian / Killing Victims
	EntityLandCivilian_CivilianVictimOfAnAttemptedCrime  Entity = 110700 // Civilian / Victim of an Attempted Crime
	EntityLandCivilian_CivilianSpy                       Entity = 110800 // Civilian / Spy
	EntityLandCivilian_CivilianCompositeLoss             Entity = 110900 // Civilian / Composite Loss
	EntityLandCivilian_CivilianEmergencyMedicalOperation Entity = 111000 // Civilian / Emergency Medical Operation
)
