// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 53 (Signals intelligence).
const (
	// EntitySIGINTSeaSurface_SignalInterceptSignalIntercept is Signal Intercept / Signal Intercept.
	EntitySIGINTSeaSurface_SignalInterceptSignalIntercept Entity = 110000

	// EntitySIGINTSeaSurface_SignalInterceptCommunications is Signal Intercept / Communications.
	EntitySIGINTSeaSurface_SignalInterceptCommunications Entity = 110100

	// EntitySIGINTSeaSurface_SignalInterceptJammer is Signal Intercept / Jammer.
	EntitySIGINTSeaSurface_SignalInterceptJammer Entity = 110200

	// EntitySIGINTSeaSurface_SignalInterceptRadar is Signal Intercept / Radar.
	EntitySIGINTSeaSurface_SignalInterceptRadar Entity = 110300
)
