// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Space missile.tsv (APP-6 E)

package app6d

// Entity constants for symbol set 06 (Space missile).
const (
	// EntitySpaceMissile_Missile is Missile.
	EntitySpaceMissile_Missile Entity = 110000
)
