// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 54 (Signals intelligence).
const (
	Modifier2SIGINTSubsurface_Disused Modifier2 = 1 // {Disused}
)
