// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Space sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 05 (Space).
const (
	Modifier1Space_LowEarthOrbitLEO       Modifier1 = 1 // Low Earth Orbit (LEO)
	Modifier1Space_MediumEarthOrbitMEO    Modifier1 = 2 // Medium Earth Orbit  (MEO)
	Modifier1Space_HighEarthOrbitHEO      Modifier1 = 3 // High Earth Orbit  (HEO)
	Modifier1Space_GeosynchronousOrbitGSO Modifier1 = 4 // Geosynchronous Orbit (GSO)
	Modifier1Space_GeostationaryOrbitGO   Modifier1 = 5 // Geostationary Orbit (GO)
	Modifier1Space_MolniyaOrbitMO         Modifier1 = 6 // Molniya Orbit (MO)
	Modifier1Space_Disused                Modifier1 = 7 // {Disused}
)
