// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Land civilian sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 11 (Land civilian).
const (
	Modifier1LandCivilian_Disused                                                        Modifier1 = 1  // {Disused}
	Modifier1LandCivilian_Disused_02                                                     Modifier1 = 2  // {Disused}
	Modifier1LandCivilian_MurderVictims                                                  Modifier1 = 3  // Murder Victims
	Modifier1LandCivilian_Disused_04                                                     Modifier1 = 4  // {Disused}
	Modifier1LandCivilian_Disused_05                                                     Modifier1 = 5  // {Disused}
	Modifier1LandCivilian_Disused_06                                                     Modifier1 = 6  // {Disused}
	Modifier1LandCivilian_Disused_07                                                     Modifier1 = 7  // {Disused}
	Modifier1LandCivilian_Disused_08                                                     Modifier1 = 8  // {Disused}
	Modifier1LandCivilian_DisplacedPersonSRefugeeSAndEvacueeS                            Modifier1 = 9  // Displaced Person(s), Refugee(s) and Evacuee(s)
	Modifier1LandCivilian_ForeignFighterS                                                Modifier1 = 10 // Foreign Fighter(s)
	Modifier1LandCivilian_GangMemberOrGang                                               Modifier1 = 11 // Gang Member or Gang
	Modifier1LandCivilian_Disused_12                                                     Modifier1 = 12 // {Disused}
	Modifier1LandCivilian_LeaderOrLeadership                                             Modifier1 = 13 // Leader or Leadership
	Modifier1LandCivilian_NongovernmentalOrganizationMemberOrNongovernmentalOrganization Modifier1 = 14 // Nongovernmental Organization Member or Nongovernmental Organization
	Modifier1LandCivilian_UnwillingCoercedRecruit                                        Modifier1 = 15 // Unwilling/Coerced Recruit
	Modifier1LandCivilian_WillingRecruit                                                 Modifier1 = 16 // Willing Recruit
	Modifier1LandCivilian_ReligiousOrReligiousOrganization                               Modifier1 = 17 // Religious or Religious Organization
	Modifier1LandCivilian_TargetedIndividualOrOrganization                               Modifier1 = 18 // Targeted Individual or Organization
	Modifier1LandCivilian_TerroristOrTerroristOrganization                               Modifier1 = 19 // Terrorist or Terrorist Organization
	Modifier1LandCivilian_Speaker                                                        Modifier1 = 20 // Speaker
	Modifier1LandCivilian_Disused_21                                                     Modifier1 = 21 // {Disused}
	Modifier1LandCivilian_Disused_22                                                     Modifier1 = 22 // {Disused}
	Modifier1LandCivilian_Other                                                          Modifier1 = 23 // Other
	Modifier1LandCivilian_Loot                                                           Modifier1 = 24 // Loot
	Modifier1LandCivilian_Disused_25                                                     Modifier1 = 25 // {Disused}
	Modifier1LandCivilian_Disused_26                                                     Modifier1 = 26 // {Disused}
)
