// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 50 (Signals intelligence).
const (
	Modifier1SIGINTSpace_AntiAircraftFireControl                Modifier1 = 1  // Anti-Aircraft Fire Control
	Modifier1SIGINTSpace_AirborneSearchAndBombing               Modifier1 = 2  // Airborne Search and Bombing
	Modifier1SIGINTSpace_AirborneIntercept                      Modifier1 = 3  // Airborne Intercept
	Modifier1SIGINTSpace_Altimeter                              Modifier1 = 4  // Altimeter
	Modifier1SIGINTSpace_AirborneReconnaissanceAndMapping       Modifier1 = 5  // Airborne Reconnaissance and Mapping
	Modifier1SIGINTSpace_AirTrafficControl                      Modifier1 = 6  // Air Traffic Control
	Modifier1SIGINTSpace_BeaconTransponderNotIFF                Modifier1 = 7  // Beacon Transponder (not IFF)
	Modifier1SIGINTSpace_BattlefieldSurveillance                Modifier1 = 8  // Battlefield Surveillance
	Modifier1SIGINTSpace_ControlledApproach                     Modifier1 = 9  // Controlled Approach
	Modifier1SIGINTSpace_ControlledIntercept                    Modifier1 = 10 // Controlled Intercept
	Modifier1SIGINTSpace_CellularMobile                         Modifier1 = 11 // Cellular/Mobile
	Modifier1SIGINTSpace_CoastalSurveillance                    Modifier1 = 12 // Coastal Surveillance
	Modifier1SIGINTSpace_DecoyMimic                             Modifier1 = 13 // Decoy/Mimic
	Modifier1SIGINTSpace_DataTransmission                       Modifier1 = 14 // Data Transmission
	Modifier1SIGINTSpace_EarthSurveillance                      Modifier1 = 15 // Earth Surveillance
	Modifier1SIGINTSpace_EarlyWarning                           Modifier1 = 16 // Early Warning
	Modifier1SIGINTSpace_FireControl                            Modifier1 = 17 // Fire Control
	Modifier1SIGINTSpace_GroundMapping                          Modifier1 = 18 // Ground Mapping
	Modifier1SIGINTSpace_HeightFinding                          Modifier1 = 19 // Height Finding
	Modifier1SIGINTSpace_HarborSurveillance                     Modifier1 = 20 // Harbor Surveillance
	Modifier1SIGINTSpace_IdentificationFriendOrFoeInterrogator  Modifier1 = 21 // Identification, Friend or Foe (Interrogator)
	Modifier1SIGINTSpace_InstrumentLandingSystem                Modifier1 = 22 // Instrument Landing System
	Modifier1SIGINTSpace_IonosphericSounding                    Modifier1 = 23 // Ionospheric Sounding
	Modifier1SIGINTSpace_IdentificationFriendOrFoeTransponder   Modifier1 = 24 // Identification, Friend or Foe (Transponder)
	Modifier1SIGINTSpace_BarrageJammer                          Modifier1 = 25 // Barrage Jammer
	Modifier1SIGINTSpace_ClickJammer                            Modifier1 = 26 // Click Jammer
	Modifier1SIGINTSpace_DeceptiveJammer                        Modifier1 = 27 // Deceptive Jammer
	Modifier1SIGINTSpace_FrequencySweptJammer                   Modifier1 = 28 // Frequency Swept Jammer
	Modifier1SIGINTSpace_JammerGeneral                          Modifier1 = 29 // Jammer (general)
	Modifier1SIGINTSpace_NoiseJammer                            Modifier1 = 30 // Noise Jammer
	Modifier1SIGINTSpace_PulsedJammer                           Modifier1 = 31 // Pulsed Jammer
	Modifier1SIGINTSpace_RepeaterJammer                         Modifier1 = 32 // Repeater Jammer
	Modifier1SIGINTSpace_SpotNoiseJammer                        Modifier1 = 33 // Spot Noise Jammer
	Modifier1SIGINTSpace_TransponderJammer                      Modifier1 = 34 // Transponder Jammer
	Modifier1SIGINTSpace_MissileAcquisition                     Modifier1 = 35 // Missile Acquisition
	Modifier1SIGINTSpace_MissileControl                         Modifier1 = 36 // Missile Control
	Modifier1SIGINTSpace_MissileDownlink                        Modifier1 = 37 // Missile Downlink
	Modifier1SIGINTSpace_Meteorological                         Modifier1 = 38 // Meteorological
	Modifier1SIGINTSpace_MultiFunction                          Modifier1 = 39 // Multi-Function
	Modifier1SIGINTSpace_MissileGuidance                        Modifier1 = 40 // Missile Guidance
	Modifier1SIGINTSpace_MissileHoming                          Modifier1 = 41 // Missile Homing
	Modifier1SIGINTSpace_MissileTracking                        Modifier1 = 42 // Missile Tracking
	Modifier1SIGINTSpace_NavigationalGeneral                    Modifier1 = 43 // Navigational/General
	Modifier1SIGINTSpace_NavigationalDistanceMeasuringEquipment Modifier1 = 44 // Navigational/Distance Measuring Equipment
	Modifier1SIGINTSpace_NavigationTerrainFollowing             Modifier1 = 45 // Navigation/Terrain Following
	Modifier1SIGINTSpace_NavigationalWeatherAvoidance           Modifier1 = 46 // Navigational/Weather Avoidance
	Modifier1SIGINTSpace_OmniLineOfSightLOS                     Modifier1 = 47 // Omni-Line of Sight (LOS)
	Modifier1SIGINTSpace_ProximityUse                           Modifier1 = 48 // Proximity Use
	Modifier1SIGINTSpace_PointToPointLineOfSightLOS             Modifier1 = 49 // Point-to-Point Line of Sight (LOS)
	Modifier1SIGINTSpace_Instrumentation                        Modifier1 = 50 // Instrumentation
	Modifier1SIGINTSpace_RangeOnly                              Modifier1 = 51 // Range Only
	Modifier1SIGINTSpace_Sonobuoy                               Modifier1 = 52 // Sonobuoy
	Modifier1SIGINTSpace_SatelliteDownlink                      Modifier1 = 53 // Satellite Downlink
	Modifier1SIGINTSpace_Space                                  Modifier1 = 54 // Space
	Modifier1SIGINTSpace_SurfaceSearch                          Modifier1 = 55 // Surface Search
	Modifier1SIGINTSpace_ShellTracking                          Modifier1 = 56 // Shell Tracking
	Modifier1SIGINTSpace_SatelliteUplink                        Modifier1 = 57 // Satellite Uplink
	Modifier1SIGINTSpace_TargetAcquisition                      Modifier1 = 58 // Target Acquisition
	Modifier1SIGINTSpace_TargetIllumination                     Modifier1 = 59 // Target Illumination
	Modifier1SIGINTSpace_TroposphericScatter                    Modifier1 = 60 // Tropospheric Scatter
	Modifier1SIGINTSpace_TargetTracking                         Modifier1 = 61 // Target Tracking
	Modifier1SIGINTSpace_Unknown                                Modifier1 = 62 // Unknown
	Modifier1SIGINTSpace_VideoRemoting                          Modifier1 = 63 // Video Remoting
	Modifier1SIGINTSpace_Experimental                           Modifier1 = 64 // Experimental
	Modifier1SIGINTSpace_Disused                                Modifier1 = 65 // {Disused}
)
