// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 51 (Signals intelligence).
const (
	// Modifier2SIGINTAir_Disused is {Disused}.
	Modifier2SIGINTAir_Disused Modifier2 = 1
)
