// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Cyberspace sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 60 (Cyberspace).
const (
	Modifier2Cyberspace_Secured                  Modifier2 = 1 // Secured
	Modifier2Cyberspace_Open                     Modifier2 = 2 // Open
	Modifier2Cyberspace_ResponseActions          Modifier2 = 3 // Response Actions
	Modifier2Cyberspace_InternalDefenseMeasures  Modifier2 = 5 // Internal Defense Measures
	Modifier2Cyberspace_AdvancedPersistentThreat Modifier2 = 6 // Advanced Persistent Threat
	Modifier2Cyberspace_NationState              Modifier2 = 7 // Nation State
	Modifier2Cyberspace_NationStateSponsored     Modifier2 = 8 // Nation State Sponsored
)
