// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Signals intelligence sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 51 (Signals intelligence).
const (
	Modifier1SIGINTAir_AntiAircraftFireControl                Modifier1 = 1  // Anti-Aircraft Fire Control
	Modifier1SIGINTAir_AirborneSearchAndBombing               Modifier1 = 2  // Airborne Search and Bombing
	Modifier1SIGINTAir_AirborneIntercept                      Modifier1 = 3  // Airborne Intercept
	Modifier1SIGINTAir_Altimeter                              Modifier1 = 4  // Altimeter
	Modifier1SIGINTAir_AirborneReconnaissanceAndMapping       Modifier1 = 5  // Airborne Reconnaissance and Mapping
	Modifier1SIGINTAir_AirTrafficControl                      Modifier1 = 6  // Air Traffic Control
	Modifier1SIGINTAir_BeaconTransponderNotIFF                Modifier1 = 7  // Beacon Transponder (not IFF)
	Modifier1SIGINTAir_BattlefieldSurveillance                Modifier1 = 8  // Battlefield Surveillance
	Modifier1SIGINTAir_ControlledApproach                     Modifier1 = 9  // Controlled Approach
	Modifier1SIGINTAir_ControlledIntercept                    Modifier1 = 10 // Controlled Intercept
	Modifier1SIGINTAir_CellularMobile                         Modifier1 = 11 // Cellular/Mobile
	Modifier1SIGINTAir_CoastalSurveillance                    Modifier1 = 12 // Coastal Surveillance
	Modifier1SIGINTAir_DecoyMimic                             Modifier1 = 13 // Decoy/Mimic
	Modifier1SIGINTAir_DataTransmission                       Modifier1 = 14 // Data Transmission
	Modifier1SIGINTAir_EarthSurveillance                      Modifier1 = 15 // Earth Surveillance
	Modifier1SIGINTAir_EarlyWarning                           Modifier1 = 16 // Early Warning
	Modifier1SIGINTAir_FireControl                            Modifier1 = 17 // Fire Control
	Modifier1SIGINTAir_GroundMapping                          Modifier1 = 18 // Ground Mapping
	Modifier1SIGINTAir_HeightFinding                          Modifier1 = 19 // Height Finding
	Modifier1SIGINTAir_HarborSurveillance                     Modifier1 = 20 // Harbor Surveillance
	Modifier1SIGINTAir_IdentificationFriendOrFoeInterrogator  Modifier1 = 21 // Identification, Friend or Foe (Interrogator)
	Modifier1SIGINTAir_InstrumentLandingSystem                Modifier1 = 22 // Instrument Landing System
	Modifier1SIGINTAir_IonosphericSounding                    Modifier1 = 23 // Ionospheric Sounding
	Modifier1SIGINTAir_IdentificationFriendOrFoeTransponder   Modifier1 = 24 // Identification, Friend or Foe (Transponder)
	Modifier1SIGINTAir_BarrageJammer                          Modifier1 = 25 // Barrage Jammer
	Modifier1SIGINTAir_ClickJammer                            Modifier1 = 26 // Click Jammer
	Modifier1SIGINTAir_DeceptiveJammer                        Modifier1 = 27 // Deceptive Jammer
	Modifier1SIGINTAir_FrequencySweptJammer                   Modifier1 = 28 // Frequency Swept Jammer
	Modifier1SIGINTAir_JammerGeneral                          Modifier1 = 29 // Jammer (general)
	Modifier1SIGINTAir_NoiseJammer                            Modifier1 = 30 // Noise Jammer
	Modifier1SIGINTAir_PulsedJammer                           Modifier1 = 31 // Pulsed Jammer
	Modifier1SIGINTAir_RepeaterJammer                         Modifier1 = 32 // Repeater Jammer
	Modifier1SIGINTAir_SpotNoiseJammer                        Modifier1 = 33 // Spot Noise Jammer
	Modifier1SIGINTAir_TransponderJammer                      Modifier1 = 34 // Transponder Jammer
	Modifier1SIGINTAir_MissileAcquisition                     Modifier1 = 35 // Missile Acquisition
	Modifier1SIGINTAir_MissileControl                         Modifier1 = 36 // Missile Control
	Modifier1SIGINTAir_MissileDownlink                        Modifier1 = 37 // Missile Downlink
	Modifier1SIGINTAir_Meteorological                         Modifier1 = 38 // Meteorological
	Modifier1SIGINTAir_MultiFunction                          Modifier1 = 39 // Multi-Function
	Modifier1SIGINTAir_MissileGuidance                        Modifier1 = 40 // Missile Guidance
	Modifier1SIGINTAir_MissileHoming                          Modifier1 = 41 // Missile Homing
	Modifier1SIGINTAir_MissileTracking                        Modifier1 = 42 // Missile Tracking
	Modifier1SIGINTAir_NavigationalGeneral                    Modifier1 = 43 // Navigational/General
	Modifier1SIGINTAir_NavigationalDistanceMeasuringEquipment Modifier1 = 44 // Navigational/Distance Measuring Equipment
	Modifier1SIGINTAir_NavigationTerrainFollowing             Modifier1 = 45 // Navigation/Terrain Following
	Modifier1SIGINTAir_NavigationalWeatherAvoidance           Modifier1 = 46 // Navigational/Weather Avoidance
	Modifier1SIGINTAir_OmniLineOfSightLOS                     Modifier1 = 47 // Omni-Line of Sight (LOS)
	Modifier1SIGINTAir_ProximityUse                           Modifier1 = 48 // Proximity Use
	Modifier1SIGINTAir_PointToPointLineOfSightLOS             Modifier1 = 49 // Point-to-Point Line of Sight (LOS)
	Modifier1SIGINTAir_Instrumentation                        Modifier1 = 50 // Instrumentation
	Modifier1SIGINTAir_RangeOnly                              Modifier1 = 51 // Range Only
	Modifier1SIGINTAir_Sonobuoy                               Modifier1 = 52 // Sonobuoy
	Modifier1SIGINTAir_SatelliteDownlink                      Modifier1 = 53 // Satellite Downlink
	Modifier1SIGINTAir_Space                                  Modifier1 = 54 // Space
	Modifier1SIGINTAir_SurfaceSearch                          Modifier1 = 55 // Surface Search
	Modifier1SIGINTAir_ShellTracking                          Modifier1 = 56 // Shell Tracking
	Modifier1SIGINTAir_SatelliteUplink                        Modifier1 = 57 // Satellite Uplink
	Modifier1SIGINTAir_TargetAcquisition                      Modifier1 = 58 // Target Acquisition
	Modifier1SIGINTAir_TargetIllumination                     Modifier1 = 59 // Target Illumination
	Modifier1SIGINTAir_TroposphericScatter                    Modifier1 = 60 // Tropospheric Scatter
	Modifier1SIGINTAir_TargetTracking                         Modifier1 = 61 // Target Tracking
	Modifier1SIGINTAir_Unknown                                Modifier1 = 62 // Unknown
	Modifier1SIGINTAir_VideoRemoting                          Modifier1 = 63 // Video Remoting
	Modifier1SIGINTAir_Experimental                           Modifier1 = 64 // Experimental
	Modifier1SIGINTAir_Disused                                Modifier1 = 65 // {Disused}
)
