// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Air sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 01 (Air).
const (
	Modifier2Air_Disused       Modifier2 = 1  // {Disused}
	Modifier2Air_Disused_02    Modifier2 = 2  // {Disused}
	Modifier2Air_Disused_03    Modifier2 = 3  // {Disused}
	Modifier2Air_BoomOnly      Modifier2 = 4  // Boom–Only
	Modifier2Air_DrogueOnly    Modifier2 = 5  // Drogue–Only
	Modifier2Air_BoomAndDrogue Modifier2 = 6  // Boom and Drogue
	Modifier2Air_Disused_07    Modifier2 = 7  // {Disused}
	Modifier2Air_Disused_08    Modifier2 = 8  // {Disused}
	Modifier2Air_Disused_09    Modifier2 = 9  // {Disused}
	Modifier2Air_Disused_10    Modifier2 = 10 // {Disused}
	Modifier2Air_Downlinked    Modifier2 = 11 // Downlinked
	Modifier2Air_Disused_12    Modifier2 = 12 // {Disused}
)
