// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Air sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 01 (Air).
const (
	Modifier1Air_Disused                         Modifier1 = 1  // {Disused}
	Modifier1Air_Bomber                          Modifier1 = 2  // Bomber
	Modifier1Air_Disused_03                      Modifier1 = 3  // {Disused}
	Modifier1Air_Fighter                         Modifier1 = 4  // Fighter
	Modifier1Air_Interceptor                     Modifier1 = 5  // Interceptor
	Modifier1Air_Tanker                          Modifier1 = 6  // Tanker
	Modifier1Air_Disused_07                      Modifier1 = 7  // {Disused}
	Modifier1Air_Disused_08                      Modifier1 = 8  // {Disused}
	Modifier1Air_Passenger                       Modifier1 = 9  // Passenger
	Modifier1Air_UltraLight                      Modifier1 = 10 // Ultra Light
	Modifier1Air_AirborneCommandPostACP          Modifier1 = 11 // Airborne Command Post (ACP)
	Modifier1Air_AirborneEarlyWarningAEW         Modifier1 = 12 // Airborne Early Warning (AEW)
	Modifier1Air_Government                      Modifier1 = 13 // Government
	Modifier1Air_Disused_14                      Modifier1 = 14 // {Disused}
	Modifier1Air_Disused_15                      Modifier1 = 15 // {Disused}
	Modifier1Air_ElectronicCombatECJammer        Modifier1 = 16 // Electronic Combat (EC)/Jammer
	Modifier1Air_Patrol                          Modifier1 = 17 // Patrol
	Modifier1Air_Reconnaissance                  Modifier1 = 18 // Reconnaissance
	Modifier1Air_Trainer                         Modifier1 = 19 // Trainer
	Modifier1Air_PhotographicReconnaissance      Modifier1 = 20 // Photographic (Reconnaissance)
	Modifier1Air_PersonnelRecovery               Modifier1 = 21 // Personnel Recovery
	Modifier1Air_Disused_22                      Modifier1 = 22 // {Disused}
	Modifier1Air_Communications                  Modifier1 = 23 // Communications
	Modifier1Air_ElectronicSupportES             Modifier1 = 24 // Electronic Support (ES)
	Modifier1Air_Disused_25                      Modifier1 = 25 // {Disused}
	Modifier1Air_Disused_26                      Modifier1 = 26 // {Disused}
	Modifier1Air_Disused_27                      Modifier1 = 27 // {Disused}
	Modifier1Air_Disused_28                      Modifier1 = 28 // {Disused}
	Modifier1Air_VeryImportantPersonVIPTransport Modifier1 = 29 // Very Important Person (VIP) Transport
	Modifier1Air_CombatSearchAndRescueCSAR       Modifier1 = 30 // Combat Search and Rescue (CSAR)
	Modifier1Air_SuppressionOfEnemyAirDefenses   Modifier1 = 31 // Suppression of Enemy Air Defenses
	Modifier1Air_AntisurfaceWarfare              Modifier1 = 32 // Antisurface Warfare
	Modifier1Air_FighterBomber                   Modifier1 = 33 // Fighter/Bomber
	Modifier1Air_IntensiveCare                   Modifier1 = 34 // Intensive Care
	Modifier1Air_ElectronicAttackEA              Modifier1 = 35 // Electronic Attack (EA)
	Modifier1Air_MultiMission                    Modifier1 = 36 // Multi-Mission
	Modifier1Air_Disused_37                      Modifier1 = 37 // {Disused}
	Modifier1Air_ASWHeloLAMPS                    Modifier1 = 38 // ASW Helo- LAMPS
	Modifier1Air_ASWHeloSH60R                    Modifier1 = 39 // ASW Helo- SH-60R
	Modifier1Air_Disused_40                      Modifier1 = 40 // {Disused}
	Modifier1Air_Disused_41                      Modifier1 = 41 // {Disused}
)
