// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Space missile sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 06 (Space missile).
const (
	Modifier2SpaceMissile_ShortRange                           Modifier2 = 1  // Short Range
	Modifier2SpaceMissile_MediumRange                          Modifier2 = 2  // Medium Range
	Modifier2SpaceMissile_IntermediateRange                    Modifier2 = 3  // Intermediate Range
	Modifier2SpaceMissile_LongRange                            Modifier2 = 4  // Long Range
	Modifier2SpaceMissile_Intercontinental                     Modifier2 = 5  // Intercontinental
	Modifier2SpaceMissile_Arrow                                Modifier2 = 6  // Arrow
	Modifier2SpaceMissile_GroundBasedInterceptorGBI            Modifier2 = 7  // Ground-Based Interceptor (GBI)
	Modifier2SpaceMissile_Patriot                              Modifier2 = 8  // Patriot
	Modifier2SpaceMissile_StandardMissileTerminalPhaseSMT      Modifier2 = 9  // Standard Missile Terminal Phase (SM-T)
	Modifier2SpaceMissile_StandardMissile3SM3                  Modifier2 = 10 // Standard Missile – 3 (SM-3)
	Modifier2SpaceMissile_TerminalHighAltitudeAreaDefenseTHAAD Modifier2 = 11 // Terminal High Altitude Area Defense (THAAD)
	Modifier2SpaceMissile_Space                                Modifier2 = 12 // Space
	Modifier2SpaceMissile_CloseRangeCRBM                       Modifier2 = 13 // Close Range (CRBM)
	Modifier2SpaceMissile_Debris                               Modifier2 = 14 // Debris
	Modifier2SpaceMissile_Unknown                              Modifier2 = 15 // Unknown
)
