// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Sea subsurface sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 35 (Sea subsurface).
const (
	Modifier1SeaSubsurface_Disused                Modifier1 = 1  // {Disused}
	Modifier1SeaSubsurface_Auxiliary              Modifier1 = 2  // Auxiliary
	Modifier1SeaSubsurface_Disused_03             Modifier1 = 3  // {Disused}
	Modifier1SeaSubsurface_Disused_04             Modifier1 = 4  // {Disused}
	Modifier1SeaSubsurface_Disused_05             Modifier1 = 5  // {Disused}
	Modifier1SeaSubsurface_Disused_06             Modifier1 = 6  // {Disused}
	Modifier1SeaSubsurface_Disused_07             Modifier1 = 7  // {Disused}
	Modifier1SeaSubsurface_Disused_08             Modifier1 = 8  // {Disused}
	Modifier1SeaSubsurface_Disused_09             Modifier1 = 9  // {Disused}
	Modifier1SeaSubsurface_Disused_10             Modifier1 = 10 // {Disused}
	Modifier1SeaSubsurface_Disused_11             Modifier1 = 11 // {Disused}
	Modifier1SeaSubsurface_Disused_12             Modifier1 = 12 // {Disused}
	Modifier1SeaSubsurface_PossibleSubmarineLow1  Modifier1 = 13 // Possible Submarine Low 1
	Modifier1SeaSubsurface_PossibleSubmarineLow2  Modifier1 = 14 // Possible Submarine Low 2
	Modifier1SeaSubsurface_PossibleSubmarineHigh3 Modifier1 = 15 // Possible Submarine High 3
	Modifier1SeaSubsurface_PossibleSubmarineHigh4 Modifier1 = 16 // Possible Submarine High 4
	Modifier1SeaSubsurface_ProbableSubmarine      Modifier1 = 17 // Probable Submarine
	Modifier1SeaSubsurface_CertainSubmarine       Modifier1 = 18 // Certain Submarine
	Modifier1SeaSubsurface_AntiTorpedoTorpedo     Modifier1 = 19 // Anti-torpedo Torpedo
	Modifier1SeaSubsurface_Disused_20             Modifier1 = 20 // {Disused}
	Modifier1SeaSubsurface_Disused_21             Modifier1 = 21 // {Disused}
	Modifier1SeaSubsurface_Disused_22             Modifier1 = 22 // {Disused}
)
