// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Land installation sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 20 (Land installation).
const (
	Modifier1LandInstallation_Biological         Modifier1 = 1  // Biological
	Modifier1LandInstallation_Disused            Modifier1 = 2  // {Disused}
	Modifier1LandInstallation_Disused_03         Modifier1 = 3  // {Disused}
	Modifier1LandInstallation_Disused_04         Modifier1 = 4  // {Disused}
	Modifier1LandInstallation_Disused_05         Modifier1 = 5  // {Disused}
	Modifier1LandInstallation_Coal               Modifier1 = 6  // Coal
	Modifier1LandInstallation_Geothermal         Modifier1 = 7  // Geothermal
	Modifier1LandInstallation_Hydroelectric      Modifier1 = 8  // Hydroelectric
	Modifier1LandInstallation_NaturalGas         Modifier1 = 9  // Natural Gas
	Modifier1LandInstallation_Disused_10         Modifier1 = 10 // {Disused}
	Modifier1LandInstallation_Disused_11         Modifier1 = 11 // {Disused}
	Modifier1LandInstallation_CivilianTelephone  Modifier1 = 12 // Civilian Telephone
	Modifier1LandInstallation_CivilianTelevision Modifier1 = 13 // Civilian Television
)
