// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Control Measures sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 25 (Control Measures).
const (
	Modifier2ControlMeasure_Urban      Modifier2 = 1 // Urban
	Modifier2ControlMeasure_Water      Modifier2 = 2 // Water
	Modifier2ControlMeasure_Ground     Modifier2 = 3 // Ground
	Modifier2ControlMeasure_Vegetation Modifier2 = 4 // Vegetation
	Modifier2ControlMeasure_Obstacles  Modifier2 = 5 // Obstacles
)
