// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Activities sector 2.tsv

package app6d

// Modifier 2 constants for symbol set 40 (Activities).
const (
	Modifier2Activities_Disused    Modifier2 = 1 // {Disused}
	Modifier2Activities_Disused_02 Modifier2 = 2 // {Disused}
)
