// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Space missile sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 06 (Space missile).
const (
	// Modifier1SpaceMissile_Ballistic is Ballistic.
	Modifier1SpaceMissile_Ballistic Modifier1 = 1

	// Modifier1SpaceMissile_Space is Space.
	Modifier1SpaceMissile_Space Modifier1 = 2

	// Modifier1SpaceMissile_Interceptor is Interceptor.
	Modifier1SpaceMissile_Interceptor Modifier1 = 3

	// Modifier1SpaceMissile_Hypersonic is Hypersonic.
	Modifier1SpaceMissile_Hypersonic Modifier1 = 4
)
