// Code generated by internal/tsvgen; DO NOT EDIT.
// Source: Space missile sector 1.tsv

package app6d

// Modifier 1 constants for symbol set 06 (Space missile).
const (
	Modifier1SpaceMissile_Ballistic   Modifier1 = 1 // Ballistic
	Modifier1SpaceMissile_Space       Modifier1 = 2 // Space
	Modifier1SpaceMissile_Interceptor Modifier1 = 3 // Interceptor
	Modifier1SpaceMissile_Hypersonic  Modifier1 = 4 // Hypersonic
)
